version: "2"

services:

  postgres:
    image: postgres:9.6-alpine
    container_name: hello_postgres
    volumes:
      - ./docker_volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sonar

  sonarqube:
    image: sonarqube:7.6-community
    container_name: hello_sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      - "sonar.jdbc.username=postgres"
      - "sonar.jdbc.password=postgres"
      - "sonar.jdbc.url=jdbc:postgresql://postgres/sonar"
